# Generated by Django 3.1.3 on 2020-12-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry', models.CharField(max_length=100)),
                ('exit', models.CharField(default='Still in Campus', max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('address', models.CharField(default='', max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=100)),
                ('Reference_student', models.CharField(default='', max_length=100)),
                ('Reference_parent', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(default='/home/anupam/Backup/netmap/image.jpg', upload_to='')),
            ],
        ),
    ]
