# Generated by Django 3.1.3 on 2020-12-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20201231_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='otherIdentity',
        ),
    ]
