# Generated by Django 3.1.3 on 2020-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_remove_visitor_otheridentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='otherIdentity',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
