# Generated by Django 3.1.4 on 2021-01-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_visitor_otheridentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='otherIdentity',
            new_name='imagename',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='photo',
        ),
        migrations.AddField(
            model_name='visitor',
            name='dateofentry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='other',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
